version: '3.8'

services:
  api_sisa:
    container_name: api_sisa-v1
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./api:/app
    ports:
      - "8001:8000"
    environment:
      - USER_NO_FHIR
    #   - USER_FHIR
      - PASS_NO_FHIR
    #   - PASS_FHIR
    #   - SCOPES
      - CODE_DOMAIN
    restart: always

  sisa_nginx:
    image: nginx:latest
    container_name: sisa_nginx
    restart: always
    ports:
      - "8002:80"
    volumes:
      - ./frontend/browser:/var/www/html
      - ./configs/my-nginx-config.conf:/etc/nginx/conf.d/default.conf

  # redis:
  #   image: redis:7.4
  #   container_name: sisa_cache
  #   ports:
  #     - "6379:6379"
