server {
    listen      80;
    listen      [::]:80;
    root        /var/www/html;

    # logging
    access_log  /var/log/nginx/access.log combined buffer=512k flush=1m;
    error_log   /var/log/nginx/error.log warn;

    include /etc/nginx/mime.types;
    types {
    	application/javascript js;
        application/javascript mjs;
    }

    location / {
        alias /var/www/html/;
        try_files $uri $uri/ /index.html;
    }
    
}
